FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . .

# Collect static at build time (OK)
RUN python manage.py collectstatic --noinput

CMD python manage.py migrate && \
    gunicorn core.wsgi:application --bind 0.0.0.0:8000
